name: Copy Files from Linux to Windows

on:
  push:
    branches:
      - main  # Change to your target branch

jobs:
  transfer:
    runs-on: self-hosted  # This runs on your Linux server

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Copy Files from Linux to Windows using SCP
        run: |
          scp -r /home/integra/build1.txt ${{ secrets.WINDOWS_USER }}@${{ secrets.WINDOWS_HOST }}:"C:/Users/integra/Desktop/github-actions/"

      - name: Verify Transfer
        run: |
          ssh ${{ secrets.WINDOWS_USER }}@${{ secrets.WINDOWS_HOST }} "dir C:\\Users\\integra\\Desktop\\github-actions"
      - name: Run PowerShell Commands on Windows via SSH
        run: |
          ssh ${{ secrets.WINDOWS_USER }}@${{ secrets.WINDOWS_HOST }} "powershell -Command 'New-Service -Name \"MyDotnetApp\" -BinaryPathName \"C:\Windows\System32\dotnet.exe C:\deploy\YourApp.dll\" -Description \"Runs my .NET Core application\" -StartupType Automatic Start-Service -Name \"MyDotnetApp\"'"	    
