name: Copy Files

on:
  push:
    branches:
      - main

jobs:
  copy-files:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to Windows server
      uses: appleboy/scp-action@v0.1.7
      
      with:
        host: ${{ secrets.WINDOWS_HOST }}
        username: ${{ secrets.WINDOWS_USER }}
        password: ${{ secrets.WINDOWS_PASSWORD }}
        source: "/home/integra/build.txt"
        target: "C:\Users\integra\Desktop\github-actions"
 
